# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT djecommerce.wsgi

beta_settings:
    cloud_sql_instances: testflexnasha:us-central1:nashasinstance

runtime_config:
  python_version: 3
# [END runtime]